# Generated by Django 2.0.1 on 2018-03-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joinCourse', '0002_auto_20180314_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
    ]
